var engineering = [{"name": "Carpenter", "value": 1977}, {"name": "Hollister", "value": 3576},
				   {"name": "Snee", "value": 1702}, {"name": "Gates", "value": 1827},  
				   {"name": "Kimball", "value": 2062}, {"name": "Kimball", "value": 2062},
				   {"name": "Phillips", "value": 5617}, {"name": "Bard", "value": 3024},
				   {"name": "Duffield", "value": 17204}];

var arts = [{"name": "Goldwin Smith", "value": 999}, {"name": "White", "value": 940},
			{"name": "Klarman", "value": 353}, {"name": "Sibley", "value": 502},  
			{"name": "Morrill", "value": 695}, {"name": "Rand", "value": 3205},
			{"name": "Lincoln", "value": 1716}, {"name": "McGraw", "value": 12}]

var library = [{"name": "Olin", "value": 9313}, {"name": "Uris", "value": 5610},
			   {"name": "Mann", "value": 7224}, {"name": "Kroch", "value": 1514},
			   {"name": "Total", "value": 5914}]; 

var cornell = [{"name": "Arts Quad", "value": 8422}, {"name": "Engineering Quad", "value": 36991},
			   {"name": "Libraries", "value": 5914}];

var ny_countytoregion = {
	"Chautauqua": "Western New York",
	"Erie": "Western New York",
	"Cattaraugus": "Western New York",
	"Allegany": "Western New York",
	"Niagara": "Western New York",
	"Orleans": "Finger Lakes",
	"Monroe": "Finger Lakes",
	"Wayne": "Finger Lakes",
	"Ontario": "Finger Lakes",
	"Seneca": "Finger Lakes",
	"Yates": "Finger Lakes",
	"Livingston": "Finger Lakes",
	"Wyoming": "Finger Lakes",
	"Genesee": "Finger Lakes",
	"Steuben": "Southern Tier",
	"Chemung": "Southern Tier",
	"Tioga": "Southern Tier",
	"Broome": "Southern Tier",
	"Chenango": "Southern Tier",
	"Delaware": "Hudson Valley",
	"Tompkins": "Southern Tier",
	"Schuyler": "Southern Tier",
	"Oswego": "Central New York",
	"Onondaga": "Central New York",
	"Madison": "Central New York",
	"Cortland": "Central New York",
	"Cayuga": "Central New York",
	"Clinton": "North Country",
	"Essex": "North Country",
	"Hamilton": "North Country",
	"Lewis": "North Country",
	"Jefferson": "North Country",
	"St Lawrence": "North Country",
	"Franklin": "North Country",
	"Nassau": "Long Island",
	"Suffolk": "Long Island",
	"Richmond": "New York City",
	"Kings": "New York City",
	"Queens": "New York City",
	"Bronx": "New York City",
	"New York": "New York City",
	"Herkimer": "Mohawk Valley",
	"Oneida": "Mohawk Valley",
	"Fulton": "Mohawk Valley",
	"Montgomery": "Mohawk Valley",
	"Otsego": "Mohawk Valley",
	"Schoharie": "Mohawk Valley",
	"Warren": "Capital Region",
	"Washington": "Capital Region",
	"Saratoga": "Capital Region",
	"Albany": "Capital Region",
	"Rensselaer": "Capital Region",
	"Schenectady": "Capital Region",
	"Greene": "Capital Region",
	"Columbia": "Capital Region",
	"Sullivan": "Hudson Valley",
	"Ulster": "Hudson Valley",
	"Dutchess": "Hudson Valley",
	"Orange": "Hudson Valley",
	"Putnam": "Hudson Valley",
	"Westchester": "Hudson Valley",
	"Rockland": "Hudson Valley"
};